spring:
  main:
    web-application-type: none
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      api-key: ${QWEN_API_KEY}
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        enabled: true
        name: qwen-mcp-client
        version: 1.0.0
        stdio:
          root-change-notification: true
          connections:
            server1:
              command: java 
              args:
                - -jar
                - C:\\Users\\lliu8\\Documents\\Carson - Coding projects\\MCP\\MCP-Server\\target\\MCPServer-0.0.1-SNAPSHOT.jar  
                - --port=8080
                - --mode=production
              env:
                API_KEY: ${QWEN_API_KEY} 
                DEBUG: "true"
        toolcallback:
          enabled: true

logging:
  level:
    org.springframework.ai.deepseek: DEBUG
    org.springframework.core.env: TRACE
    root: INFO